Repository 4Subsea/drio-python, pull requests merged in 2023-02, with the labels that each got.

#54 Remove support for cache format selection, and simplify storage related code
  datareservoirio/client.py
  datareservoirio/storage/__init__.py
  datareservoirio/storage/cache_engine.py
  datareservoirio/storage/storage.py
  tests/test_client.py
  tests/test_storage/test_cache_engine.py
  tests/test_storage/test_storage.py
  tests_integration/test_client.py
  tests_integration/test_client_metadata.py
  tests_integration/test_storage/test_basedownloader_directdownload.py
  tests_integration/test_timeseries_api.py
Labels: breaking-change

#55 Fix issues with failed downloads due to SAS-key expiry
  datareservoirio/client.py
  datareservoirio/storage/__init__.py
  datareservoirio/storage/storage.py
  tests/test_client.py
  tests/test_storage/test_storage.py
Labels: bug

#56 Remove all unit and integration tests
  tests/test_authenticator.py
  tests/test_client.py
  tests/test_environments.py
  tests/test_logging.py
  tests/test_rest_api/test_base.py
  tests/test_rest_api/test_files.py
  tests/test_rest_api/test_metadata.py
  tests/test_rest_api/test_timeseries.py
  tests/test_something.py
  tests/test_storage/test_cache_engine.py
  tests/test_storage/test_storage.py
  tests/test_storage/testdata/numeric_blob.csv
  tests/test_storage/testdata/str_blob.csv
  tests_integration/__init__.py
  tests_integration/_auth.py
  tests_integration/exclude_test_large_upload_download.py
  tests_integration/test_authentication.py
  tests_integration/test_client.py
  tests_integration/test_client_metadata.py
  tests_integration/test_files_api.py
  tests_integration/test_storage/__init__.py
  tests_integration/test_storage/test_basedownloader_directdownload.py
  tests_integration/test_storage/test_basedownloader_filecachedownload.py
  tests_integration/test_timeseries_api.py
Labels: test
