Repository 4Subsea/drio-python, pull requests merged in 2023-11, with the labels that each got.

#111 Ess 2003 as a user i would like to see what the package is doing when things are taking a long time
  datareservoirio/client.py
Labels: enhancement

#107 CHORE: make test default for deployment
  .github/workflows/deploy_public.yml
Labels: chore

#112 Add possibility to log EngineRoom application ID
  datareservoirio/_constants.py
  datareservoirio/_logging.py
  tests/test__logging.py
Labels: feature

#115 update version urllib3
  pyproject.toml
Labels: bug

#113 Add possibility to log retries of client.get() as warnings
  datareservoirio/_logging.py
  datareservoirio/client.py
  tests/test__logging.py
Labels: enhancement

#114 Update docs describing the loggers
  docs/user_guide/advanced_config.rst
Labels: documentation

#116 DOCS: add link to metadata article
  docs/user_guide/manage_metadata.rst
Labels: documentation

#110 update version python
  .github/workflows/ci.yml
  .github/workflows/deploy_public.yml
  docs/getting_started.rst
  pyproject.toml
Labels: chore
