Repository 4Subsea/drio-python, pull requests merged in 2023-01, with the labels that each got.

#37 Make "show source" links in API, include inherited methods for classes
  .github/workflows/deploy_public.yml
  build_doc.bat
  docs/_templates/autosummary/class.rst
  docs/api_ref/authentication.rst
  docs/api_ref/index.rst
  docs/conf.py
  docs/release_notes.md
  docs/release_notes.rst
  tox-deploy.ini
  tox.ini
Labels: documentation

#33 Add "SasKeyExpirationTime" key to Files json in unit-tests for prep for DATARES-131
  tests/test_client.py
Labels: test

#38 Address deprecation warnings in test suite
  datareservoirio/rest_api/base.py
  tests/test_client.py
  tests/test_storage/test_cache_engine.py
  tests/test_storage/test_storage_engine.py
Labels: test

#39 Fix typos
  README.rst
  datareservoirio/client.py
  docs/index.rst
  docs/user_guide/advanced_config.rst
  docs/user_guide/index.rst
  docs/user_guide/manage_metadata.rst
  docs/user_guide/manage_series.rst
Labels: chore

#40 Clean up after deprecated login system
  datareservoirio/_constants.py
  datareservoirio/authenticate.py
Labels: refactor

#41 Make datareservoirio.Client.get() end time exclusive
  datareservoirio/client.py
  tests/test_client.py
Labels: enhancement

#44 Avoid creation of "my_dir" during tests
  .gitignore
  tests/test_authenticator.py
Labels: test

#45 Remove print statement from authentication ("authentication from previous session is still valid")
  datareservoirio/authenticate.py
  docs/api_ref/index.rst
Labels: enhancement

#47 Bug fix for metadata search and browse methods
  datareservoirio/client.py
  datareservoirio/rest_api/metadata.py
  datareservoirio/rest_api/timeseries.py
  docs/user_guide/browse_search.rst
  tests/test_client.py
  tests/test_rest_api/test_metadata.py
Labels: bug

#48 Move Series <-> DataFrame convertion out of Storage and into Client
  datareservoirio/client.py
  datareservoirio/storage/storage.py
  tests/test_client.py
  tests/test_storage/test_storage.py
Labels: refactor

#50 Update error message in metadata_get to make it clear what is missing
  datareservoirio/client.py
Labels: bug

#49 Refactor and simplify Storage.put
  datareservoirio/client.py
  datareservoirio/storage/__init__.py
  datareservoirio/storage/storage.py
  tests/test_client.py
  tests/test_storage/test_storage.py
Labels: refactor

#52 Small cleanups: typos + refactor code to remove enter and exit methods
  datareservoirio/client.py
  datareservoirio/rest_api/files.py
  tests/test_client.py
  tests/test_rest_api/test_files.py
Labels: refactor

#51 Return empty Series if no data is available in the datareservoirio
  datareservoirio/storage/storage.py
  tests/test_client.py
  tests/test_storage/test_storage.py
Labels: bug

#53 Make reading dataframe from blob robust with respect to network issues
  datareservoirio/storage/storage.py
  tests/test_storage/test_storage.py
Labels: enhancement
