Repository 4Subsea/drio-python, pull requests merged in 2024-06, with the labels that each got.

#126 Ensure sorted data on upload of data from python
  datareservoirio/client.py
  docs/user_guide/index.rst
  docs/user_guide/manage_series.rst
  tests/test_client.py
Labels: refactor

#127 Documentation on difference in time resolution between cold path and ADX
  docs/user_guide/manage_series.rst
Labels: documentation

#128 Ess 2670 update drio python documentation to let the user know that cold path and adx has different time resolution
  docs/user_guide/manage_series.rst
Labels: bug, documentation

#129 ESS-2679: Match test responses to actual ones
  tests/response_cases.py
  tests/test_client.py
  tests/testdata/response_cases/datareservoirio_metadata_api/metadata_get_id.json
  tests/testdata/response_cases/datareservoirio_metadata_api/metadata_get_ns_key.json
  tests/testdata/response_cases/datareservoirio_metadata_api/metadata_search.json
  tests/testdata/response_cases/datareservoirio_timeseries_api/info.json
  tests/testdata/response_cases/datareservoirio_timeseries_api/timeseries_metadata_delete.json
  tests/testdata/response_cases/datareservoirio_timeseries_api/timeseries_metadata_put.json
Labels: test
